repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: "ruff - lint & fix"
        entry: ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: "ruff - format"
        entry: ruff format
        language: system
        types: [python]
